#!/bin/bash
#$ -cwd
#$ -V
#$ -N call-methylation
#$ -S /bin/bash
#$ -b y
#$ -pe smp 80
#$ -l mem_requested=4G
#$ -l h_vmem=4G
#$ -l tmp_requested=150G
#$ -l nvgpu=1

#change this to the root project directory where
BASEDIR=/home/davhyl/test
#change this to where the fast5 tar is
FAST5TAR=$BASEDIR/FAB42804-84744914_Multi_Fast5.tar
#change this where the fastq tar is (note that all the .fastq files inside this tar file will be scanned recursively)
FASTQTAR=$BASEDIR/FAB42804-84744914_Multi.tar
#change the following to where the sequencing summary file is
#if you do not have it keep it empty i.e. SEQSUM="", which is recommended as Nanopore keeps on changing the sequencing summary format and thus f5c may fail
#however, f5c index will be fast if the sequencing summary given
SEQSUM=""
#change this to where you want the output to be
OUTPUT_DIR=$BASEDIR/output

#only change if the reference is not human
REFERENCE=/home/hasgam/scratch/hg38noAlt/hg38noAlt.fa

#only change if you need to run using different versions
MINIMAP=/home/hasgam/installs/minimap2-2.14/minimap2
SAMTOOLS=/home/hasgam/installs/samtools-1.9/samtools
F5C=/share/ClusterShare/software/contrib/hasgam/f5c/f5c

#number of threads to launch
num_threads=80

# Do not change anything below here unless you know what you are doing

# terminate script
die() {
	echo "$1" >&2
	echo
	exit 1
}

test -e $FAST5TAR || die "input file $FAST5TAR not found"
test -e $FASTQTAR || die "input file $FASTQTAR not found"
test -e $REFERENCE || die "reference genome $REFERENCE not found"
test -d $OUTPUT_DIR || mkdir $OUTPUT_DIR || die "Could not create directory $OUTPUT_DIR"
if [ -n $SEQSUM ]; then
	test -e $SEQSUM || die "sequencing summary file $SEQSUM not found"
fi


REF=$TMPDIR/ref/ref.fa

BASENAME=$(basename $FAST5TAR)
BASENAME=${BASENAME%.tar}

FASTQ=$TMPDIR/$BASENAME.fastq
SAM=$TMPDIR/out/$BASENAME.sam
BAM=$TMPDIR/out/$BASENAME.bam
METH=$TMPDIR/out/$BASENAME"_per_read_methcalls.tsv"
METH_FREQ=$TMPDIR/out/$BASENAME"_meth_frequencies.tsv"

mkdir $TMPDIR/fastq  $TMPDIR/ref/ $TMPDIR/fast5 $TMPDIR/out/ || die "Could not create temporary directories at $TMPDIR"

echo "Copying reference $REFERENCE to $REF"
cp $REFERENCE  $REF || die "Copying $REFERENCE to $REF failed"

echo "Extracting fastq tar"
/usr/bin/time -v tar xf $FASTQTAR -C $TMPDIR/fastq/ || die "Extracting $FASTQTAR to $TMPDIR/fastq/ failed"

numfastq=$(find $TMPDIR/fastq/ -name '*.fastq' | wc -l)
[ "$numfastq" = 0 ] && die "0 fastq files found. probably file structure is different"
echo "Concatenating $numfastq fastqs"
find $TMPDIR/fastq/ -name '*.fastq' -exec cat {} \; > $FASTQ || die "Concatenating $numfastq fastqs failed"

cd $TMPDIR

#minimap
echo "Minimap2 running"
/usr/bin/time -v $MINIMAP -x map-ont -a -t$num_threads --secondary=no $REF $FASTQ > $SAM  || die "minimap2 failed"
echo "copying minimap2 results data back"
cp $SAM $OUTPUT_DIR/ || die "copying minimap2 results data back failed"

#sorting
echo "samtools sorting"
/usr/bin/time -v $SAMTOOLS sort -@$num_threads $SAM > $BAM || die "samtools failed"
/usr/bin/time -v $SAMTOOLS index $BAM || die "samtools index failed"
echo "copying samtools results back"
cp $BAM $OUTPUT_DIR/ || die "copying samtools results back"

echo "Extracting fast5 tar. This will take ages."
/usr/bin/time -v tar xf $FAST5TAR -C $TMPDIR/fast5/ || die "Extracting $FAST5TAR to $TMPDIR/fast5/ failed"

#index
if [ -z $SEQSUM ]; then
	echo "Indexing the fast5 - will take ages as the sequencing summary file is not specified"
	/usr/bin/time -v $F5C index -d fast5/ $FASTQ || die "f5c index failed"
else
	echo "Indexing the fast5 using the sequencing summary file $SEQSUM"
	/usr/bin/time -v $F5C index -d fast5/ $FASTQ -s $SEQSUM  || die "f5c index failed"
fi

#methylation calling
echo "Methylation calling"
/usr/bin/time -v $F5C call-methylation -t $num_threads -r  $FASTQ -g $REF -b $BAM -K 1024 -B 10M --cuda-max-lf 5.0 --iop 16  > $METH || die "f5c methylation calling failed"
echo "copying methylation calling results"
cp $METH $OUTPUT_DIR/ || die "copying methylation calling results failed"

# echo "Methylation frequencies"
# /usr/bin/time -v $F5C meth-freq -i $METH -s > $METH_FREQ || die "f5c methylation frequency failed"
# echo "copying methylation frequency results"
# cp $METH_FREQ $OUTPUT_DIR/ || die "copying methylation frequency results failed"

echo "all done"
